# Generated by Django 4.1.5 on 2023-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=4000, null=True)),
                ('fact', models.CharField(blank=True, max_length=20, null=True)),
                ('traits', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
