# Generated by Django 4.1.5 on 2023-10-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_fact_dog_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('age_2', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_2', models.CharField(blank=True, max_length=4000, null=True)),
                ('height_2', models.CharField(blank=True, max_length=20, null=True)),
                ('traits_2', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url_2', models.ImageField(blank=True, max_length=50, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_url',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
    ]
