# Generated by Django 4.1.5 on 2023-12-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_dog_2_alter_dog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='height',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
